- src/components/common/Layout.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/routes/router.tsx
-  Header 컴포넌트를 Layout.tsx에서 관리
- #1 
-
> Refactor: Header 컴포넌트를 Layout.tsx에서 관리

- src/components/pages/login/FindPasswordPage.tsx
- src/components/pages/login/ResetPasswordPage.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/login/SignUpPage.tsx
- src/components/pages/login/TermsPage.tsx
- src/routes/router.tsx
- 로그인페이지 비밀번호변경 및 회원가입 페이지 일부 생성
- #7 
- 로그인페이지, 약관페이지, 회원가입 페이지, 비밀번호변경 페이지 일부 생성했고 제가 맡은 부분 스타일은 8-90% 정도 이번 주말까지 마무리 하겠습니다.
> Feature: 로그인페이지 비밀번호변경 및 회원가입 페이지 일부 구현

- src/assets/icons/goodbuyus-logo.svg
- src/components/common/Header.tsx
- src/components/pages/HomePage/CategoryProduct.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/HomePage/PopularProduct.tsx
- src/components/pages/HomePage/model/productSchema.ts
- src/components/pages/Payment/PaymentForm.tsx
- src/components/pages/Payment/PaymentSuccessPage.tsx
- src/components/pages/Payment/api/paymentApi.ts
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/ProductPage/ProductPage.tsx
- src/main.tsx
- src/routes/router.tsx
- 상품 구매 완료 페이지 생성
- 다른 페이지들 디자인 수정 및 api 호출 코드 변경
- #1  #14 
- api 호출부분에서 react-query를 사용해서 작성했는데 api 적용 전까지는 오류가 있을지는 잘 모르겠습니다.
> Feat: 상품 구매 완료 페이지 생성

- .env
> Remove: .env 삭제

- src/components/pages/ProductDetailPage/ProductDetail.tsx
- import부분 오타 수정 (다시올립니다 ㅜㅜ)
-
-
> Fix: import부분 오타 수정

- src/api/loginApi.ts
- src/api/mypageApi.ts
- src/components/pages/login/FindPasswordPage.tsx
- src/components/pages/login/ResetPasswordPage.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/login/SignUpPage.tsx
- src/components/pages/myPage/LocationPage.tsx
- src/components/pages/myPage/Modal/PasswordModal.tsx
- 로그인,회원가입,비밀번호찾기,리셋,현재비밀번호 확인, 동네변경 api 로직 추가
- #7 #13 
- 서버 주소 받고 api 연동 작업 진행하는데 CORS 오류가 전체 다 떠서 해당 사항 담당하시는 백엔드 팀원분께 공유드렸습니다. pr 올리기 전까지도 확인했는데 오류가 계속 떠있어서 해결하시는대로 로그인회원가입쪽 api 마무리 하겠습니다.
> Feat: 로그인,회원가입,비밀번호찾기,리셋,현재비밀번호 확인, 동네변경 api 로직 추가

- src/api/axiosInstance.ts
- src/api/loginApi.ts
- src/components/pages/login/SetLocationPage.tsx
- src/components/pages/login/SetNicknamePage.tsx
- src/components/pages/login/SetProfilePage.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/login/SignUpPage.tsx
- vite.config.mts
- api 형식 변경 및 회원가입, 위치, 닉네임, 로그인 api 연동 완료
- token, role 정보 localstorage에 저장
- #7 
- cors 해결해주셔서 로그인파트 api 연동 완료했습니다.
> Feat: 회원가입, 로그인 파트 api 연동 완료 

- src/components/pages/ProductDetailPage/ProductDetail.tsx
> Chore: 찜기능 주석처리

- src/api/loginApi.ts
- role 지워진 부분 추가
- #7 
-  role 지워진 부분 추가했습니다
> Feat: role 추가

- src/api/mypageApi.ts
- src/components/common/Header.tsx
- src/components/pages/login/FindPasswordPage.tsx
- src/components/pages/login/LoginCompletePage.tsx
- src/components/pages/login/ResetPasswordPage.tsx
- src/components/pages/login/SetLocationPage.tsx
- src/components/pages/login/SetNicknamePage.tsx
- src/components/pages/login/SetProfilePage.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/login/SignUpPage.tsx
- src/components/pages/login/TermsPage.tsx
- src/components/pages/myPage/LocationPage.tsx
- src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
- src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
- src/components/pages/myPage/SettingPage.tsx
- 닉네임, 환불 소셜로그인 api 적용
- api 실패 시 알람 추가
- 주소 풀네임으로 변경
- #7 #13 
-
> Feat: 닉네임, 환불 소셜로그인 api 적용, api 실패 시 알람 추가, 주소 풀네임으로 변경

- src/components/pages/myPage/SettingPage.tsx
- src/components/pages/myPage/SideMenu.tsx
> feat: 프로필 이미지 (#13)

- .github/workflows/cicd.yml
- s3로 배포 자동화하기 위해 CI/CD 추가
-
-
> Feat: CI/CD 추가

- src/api/loginApi.ts
- src/components/common/ChatRoom.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/HomePage/api/productApi.ts
- src/components/pages/Payment/PaymentSuccessPage.tsx
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/ProductDetailPage/api/productDetailApi.ts
- src/components/pages/myPage/LocationPage.tsx
- src/components/pages/myPage/SettingPage.tsx
- src/context/AuthContext.tsx
- src/context/LocationContext.tsx
- src/main.tsx
- src/utils/webSocket.ts
- aws 이동에 따른 api 엔드포인트 변경
- 마이페이지 변경
-
-
> refactor: api 엔드포인트 변경 및 마이페이지 변경

- src/components/common/ChatRoom.tsx
- src/components/pages/HomePage/CategoryProduct.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/HomePage/RecommendProduct.tsx
- src/components/pages/HomePage/api/productApi.ts
- src/components/pages/HomePage/model/productSchema.ts
- src/components/pages/ProductDetailPage/CommentComponent.tsx
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/ProductPage/ProductComponent.tsx
- src/components/pages/community/modal/ChatRoomModal.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/myPage/ChatListPage.tsx
- src/components/pages/myPage/LocationPage.tsx
- src/components/pages/myPage/Modal/LogoutModal.tsx
- src/components/pages/myPage/Modal/PasswordModal.tsx
- src/components/pages/myPage/Modal/WithdrawModal.tsx
- src/components/pages/myPage/MyPostsPage.tsx
- src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
- src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
- src/components/pages/myPage/OrderListPage.tsx
- src/components/pages/myPage/SettingPage.tsx
- src/components/pages/myPage/SideMenu.tsx
- src/components/pages/myPage/WishListPage.tsx
- src/routes/router.tsx
- 마이페이지 디자인 및 기능 수정
- 마이페이지 전체 css 수정 및 알림페이지 삭제
- 상단상품 댓글 기능에서 userid 반영하여 로직 수정 및 사용자 프로필, 닉네임 보이게 수정(본인 이외에는 익명 표기)
- 기본 홈페이지에 접근시 필수적으로 로그인을 하도록 첫 시작 페이지를 로그인페이지로 변경
- #63 
-
> Refactor: 마이페이지 작업 및 프론트 전체 기능 수정

- src/components/pages/myPage/LocationPage.tsx
- src/types/kakao.d.ts
- src/utils/kakaoMapLoader.ts
> Fix: 카카오 맵 api 사용법 변경

- .github/workflows/cicd.yml
- 배포를 위해 카카오 맵 api 키를 ci/cd에 환경변수로 추가
-
-
> Fix: 카카오맵 api키 ci/cd 추가

- .github/workflows/cicd.yml
- .env 파일 추가해서 카카오맵 api키를 넣는 방식으로 변경
-
-
> Fix: 카카오맵 api키 환경변수 방식 변경

- .github/workflows/cicd.yml
- CI/CD 환경변수에 VITE_API_URL 추가
-
-
> fix: VITE_API_URL 추가

- .github/workflows/cicd.yml
- 두번째 환경변수 >로 하면 덮어쓰기 되어서 >>로 변경
-
-
> Fix: ci/cd env 수정

- cypress.config.ts
- cypress/e2e/login.cy.ts
- cypress/e2e/main.cy.ts
- cypress/e2e/mypage.cy.ts
- cypress/e2e/order.cy.ts
- cypress/e2e/productDetail.cy.ts
- cypress/fixtures/example.json
- cypress/support/commands.ts
- cypress/support/e2e.ts
- package-lock.json
- package.json
- src/api/loginApi.ts
- src/api/mypageApi.ts
- src/components/common/Header.tsx
- src/components/pages/HomePage/CategoryProduct.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/Payment/PaymentForm.tsx
- src/components/pages/ProductDetailPage/CommentComponent.tsx
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/ProductPage/ProductComponent.tsx
- src/components/pages/community/PostDetailPage/PostCommentsSection.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/myPage/Modal/PasswordModal.tsx
- src/components/pages/myPage/SettingPage.tsx
- src/components/pages/myPage/SideMenu.tsx
- src/routes/router.tsx
- src/utils/GetImageSrc.tsx
- src/utils/webSocket.ts
- 마이페이지 닉네임, 프로필 변경 추가
- 이미지 처리
- e2e 테스트 코드 추가 
- #63 
-
> Feat: 마이페이지 닉네임, 프로필 변경 추가, 이미지 처리, e2e 테스트 코드 추가 

- src/api/chatApi.ts
- src/api/loginApi.ts
- src/api/mypageApi.ts
- src/components/common/ChatRoom.tsx
- src/components/common/Pagination.tsx
- src/components/common/StarRating.tsx
- src/components/common/styles/CardStyles.ts
- src/components/pages/HomePage/CategoryProduct.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/HomePage/PopularProduct.tsx
- src/components/pages/HomePage/RecommendProduct.tsx
- src/components/pages/HomePage/style/CardStyle.tsx
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/ProductPage/ProductComponent.tsx
- src/components/pages/ProductPage/ProductPage.tsx
- src/components/pages/community/PostEditPage.tsx
- src/components/pages/login/SetNicknamePage.tsx
- src/components/pages/myPage/ChatListPage.tsx
- src/components/pages/myPage/MyPostsPage.tsx
- src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
- src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
- src/components/pages/myPage/OrderListComponents/RefundHistory.tsx
- src/components/pages/myPage/SettingPage.tsx
- src/components/pages/myPage/SideMenu.tsx
- src/components/pages/myPage/WishListPage.tsx
- 채팅방 실시간 소통이 안되던 오류 수정
- 채팅방 날짜 구분선 표시
- 게시글 수정 페이지에서 데이터 불러오는 타이밍 변경
- 마이페이지 프로필 변경 오류 수정 및 닉네 임 변경모달 css 수정, 닉네임 최대 길이 설정
- 채팅방 메세지 두번 보내지는 오류 수정 -> 로컬에서의 메세지 표출 삭제
- 마이페이지 페이지네이션 추가
- 카드 컴포넌트 디자인 수정 및 별점 표기 오류 수정
- 상단 배너에 표기되는 인기상품 디자인 변경
- #73 #63 
-
> Feat : 프론트 전체적으로 오류 점검 및 수정

- src/components/common/Header.tsx
- src/components/pages/Payment/PaymentForm.tsx
- src/components/pages/ProductPage/ProductComponent.tsx
- src/components/pages/ProductPage/ProductPage.tsx
- src/components/pages/myPage/MyPostsPage.tsx
- src/utils/webSocket.ts
- 상단상품 결제페이지 뒤로가기 버튼 오류 수정]
- 마이페이지 내 글 삭제시 화면 리렌더링되도록 수정
- productpage에서 필터링 버튼 추가(카테고리, 가격순, 별점 순)
- productpage로 카테고리 옮기는 방식 수정
- websocket에서 웹소켓주소를 .env를 참조하도록 변경
- 헤더 디자인 변경
- #74 #73 
-
> Feat: 프론트엔드 전체 기능 점검 및 수정

- src/api/reviewApi.ts
- src/components/common/PostItem.tsx
- src/components/common/PostList.tsx
- src/components/common/ReviewModal.tsx
- src/components/common/StarRating.tsx
- src/components/pages/HomePage/CategoryProduct.tsx
- src/components/pages/HomePage/HomePage.tsx
- src/components/pages/HomePage/PopularProduct.tsx
- src/components/pages/HomePage/RecommendProduct.tsx
- src/components/pages/HomePage/style/CardStyle.tsx
- src/components/pages/Payment/AuthorForm.tsx
- src/components/pages/Payment/PaymentForm.tsx
- src/components/pages/ProductDetailPage/ProductDetail.tsx
- src/components/pages/login/SignInPage.tsx
- src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
- src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
- src/components/pages/myPage/ReviewPage.tsx
- src/components/pages/myPage/SettingPage.tsx
- src/components/pages/myPage/SideMenu.tsx
- src/hooks/useUserReview.tsx
- src/routes/router.tsx
- src/types/review.ts
- 사용자 리뷰 작성시에 내가 작성한 글은 리뷰 작성이 보이지 않도록 변경, 이미 작성한 리뷰는 재작성 불가능하도록 변경
- 홈페이지 추천상품 정렬기준 변경
- 인기상품을 마감임박 상품으로 교체
- 주문 목록을 최신순으로 보여주도록 수정
- 사용자 리뷰 모달 디자인 변경 및 이미 작성한 리뷰 alert 추가
- 마이페이지에 내 리뷰 페이지 생성 마이페이지 내 리뷰페이지 css 수정 및 로고 변경
- 사용자 리뷰가 4.0 이상인 경우 커뮤니티 게시글 사용자명 옆에 배지 추가
- starRating 이모티콘 변경
- 소셜로그인 기능 삭제
- #75 
-
> Feat: 프론트엔드 전반적 리팩토링

- src/components/common/PostItem.tsx
- src/components/common/PostList.tsx
- src/components/common/SearchPostBar.tsx
- src/components/pages/ProductPage/ProductComponent.tsx
- src/components/pages/myPage/ChatListPage.tsx
- src/components/pages/myPage/MyPostsPage.tsx
- src/components/pages/myPage/OrderListComponents/GroupPurchaseHistory.tsx
- src/components/pages/myPage/OrderListComponents/OrderHistory.tsx
- src/components/pages/myPage/ReviewPage.tsx
- src/components/pages/myPage/WishListPage.tsx
- src/hooks/useUserReview.tsx
- tsconfig.json
- 페이지네이션으로 페이지 이동시 상단 스크롤
- 배지가 없는 사용자의 닉네임 표기 오류 수정
- 커뮤니티 게시글 리뷰순서로 정렬, 내 게시글이면 상단에 정렬
- 커뮤니티 게시글 페이지에 검색바 추가
- #78 
-
> Refactor: 프론트엔드 전반적인 기능 점검
